---
kind: pipeline
name: check

steps:
  - name: restore-cache
    image: meltwater/drone-cache:v1
    pull: always
    settings:
      backend: "filesystem"
      restore: true
      cache_key: '{{ .Repo.Name }}_slim_{{ checksum "Cargo.lock" }}_{{ arch }}_{{ os }}'
      archive_format: "gzip"
      mount:
        - "target"
    volumes:
      - name: cache
        path: /tmp/cache
  
  - name: check
    image: rust:slim
    pull: always
    environment:
      CARGO_HOME: target/cargo
      RUST_BACKTRACE: 1
    commands:
      - cargo -V
      - cargo check
  
  - name: rebuild-cache
    image: meltwater/drone-cache:v1
    pull: always
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: '{{ .Repo.Name }}_slim_{{ checksum "Cargo.lock" }}_{{ arch }}_{{ os }}'
      archive_format: "gzip"
      mount:
        - "target"
    volumes:
      - name: cache
        path: /tmp/cache

volumes:
  - name: cache
    host:
      path: /var/lib/cache

---
kind: pipeline
name: rustfmt

steps:
  - name: rustfmt
    image: iamsauravsharma/rust-fmt:nightly-alpine
    pull: always
    commands:
      - cargo fmt -- -V
      - cargo fmt -- --check -l

---
kind: pipeline
name: build

depends_on:
  - check
trigger:
  branch:
    - master
  event:
    - cron
    - custom
    - push
  status:
    - success

steps:
  - name: restore-cache
    image: meltwater/drone-cache:v1
    pull: always
    settings:
      backend: "filesystem"
      restore: true
      cache_key: '{{ .Repo.Name }}_alpine_{{ checksum "Cargo.lock" }}_{{ arch }}_{{ os }}'
      archive_format: "gzip"
      mount:
        - "target"
    volumes:
      - name: cache
        path: /tmp/cache
  
  - name: build
    image: alpine:3.12
    pull: always
    environment:
      CARGO_HOME: target/cargo
    commands:
      - apk add --no-cache cargo rust
      - cargo -V
      - cargo build
  
  - name: secrets
    image: busybox
    pull: always
    environment:
      ABUILD_PUBKEY:
        from_secret: ABUILD_PUBKEY
      ABUILD_PRIVKEY:
        from_secret: ABUILD_PRIVKEY
    commands:
      - echo "$$ABUILD_PUBKEY" >alpine@msrd0.de-5fc3c0b2.rsa.pub
      - echo "$$ABUILD_PRIVKEY" >alpine@msrd0.de-5fc3c0b2.rsa
  
  - name: run
    image: docker
    pull: always
    environment:
      ABUILD_PUBKEY:
        from_secret: ABUILD_PUBKEY
      ABUILD_PRIVKEY:
        from_secret: ABUILD_PRIVKEY
      RUST_LOG: info
    commands:
      - apk add --no-cache libgcc
      - docker -v
      - ./target/debug/alpine-rust
      - docker ps -a
    volumes:
      - name: dockersock
        path: /var/run
  
  - name: rebuild-cache
    image: meltwater/drone-cache:v1
    pull: always
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: '{{ .Repo.Name }}_alpine_{{ checksum "Cargo.lock" }}_{{ arch }}_{{ os }}'
      archive_format: "gzip"
      mount:
        - "target"
    volumes:
      - name: cache
        path: /tmp/cache

environment:
  RUST_BACKTRACE: 1

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: cache
    host:
      path: /var/lib/cache
  - name: dockersock
    temp: {}

...
