---
kind: pipeline
name: check

steps:
  - name: restore-cache
    image: meltwater/drone-cache:v1
    pull: always
    settings:
      backend: "filesystem"
      restore: true
      cache_key: '{{ .Repo.Name }}_{{ checksum "Cargo.lock" }}_{{ arch }}_{{ os }}'
      archive_format: "gzip"
      mount:
        - "target"
    volumes:
      - name: cache
        path: /tmp/cache
  
  - name: check
    image: rust:stable
    pull: always
    environment:
      CARGO_HOME: target/cargo
      RUST_BACKTRACE: 1
    commands:
      - cargo -V
      - cargo check
  
  - name: rebuild-cache
    image: meltwater/drone-cache:v1
    pull: always
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: '{{ .Repo.Name }}_{{ checksum "Cargo.lock" }}_{{ arch }}_{{ os }}'
      archive_format: "gzip"
      mount:
        - "target"
    volumes:
      - name: cache
        path: /tmp/cache

volumes:
  - name: cache
    host:
      path: /var/lib/cache

---
kind: pipeline
name: rustfmt

steps:
  - name: rustfmt
    image: iamsauravsharma/rust-fmt:nightly-alpine
    pull: always
    commands:
      - cargo fmt -- -V
      - cargo fmt -- --check -l

...
