---
kind: pipeline
name: check

steps:
  - name: restore-cache
    image: meltwater/drone-cache:v1
    pull: always
    settings:
      backend: "filesystem"
      restore: true
      cache_key: '{{ .Repo.Name }}_{{ checksum "Cargo.lock" }}_{{ arch }}_{{ os }}'
      archive_format: "gzip"
      mount:
        - "target"
    volumes:
      - name: cache
        path: /tmp/cache
  
  - name: check
    image: rust:slim
    pull: always
    environment:
      CARGO_HOME: target/cargo
      RUST_BACKTRACE: 1
    commands:
      - cargo -V
      - cargo check
  
  - name: rebuild-cache
    image: meltwater/drone-cache:v1
    pull: always
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: '{{ .Repo.Name }}_{{ checksum "Cargo.lock" }}_{{ arch }}_{{ os }}'
      archive_format: "gzip"
      mount:
        - "target"
    volumes:
      - name: cache
        path: /tmp/cache

volumes:
  - name: cache
    host:
      path: /var/lib/cache

---
kind: pipeline
name: rustfmt

steps:
  - name: rustfmt
    image: iamsauravsharma/rust-fmt:nightly-alpine
    pull: always
    commands:
      - cargo fmt -- -V
      - cargo fmt -- --check -l

---
kind: pipeline
name: build

depends_on:
  - check
trigger:
  branch:
    - master
  event:
    - cron
    - custom
    - push
  status:
    - success

steps:
  - name: restore-cache
    image: meltwater/drone-cache:v1
    pull: always
    settings:
      backend: "filesystem"
      restore: true
      cache_key: '{{ .Repo.Name }}_{{ checksum "Cargo.lock" }}_{{ arch }}_{{ os }}'
      archive_format: "gzip"
      mount:
        - "target"
    volumes:
      - name: cache
        path: /tmp/cache
  
  - name: build
    image: rust:slim
    pull: always
    environment:
      CARGO_HOME: target/cargo
      RUST_BACKTRACE: 1
    commands:
      - cargo -V
      - cargo build
      - find . -name alpine-rust -executable
  
  - name: run
    image: docker
    pull: always
    environment:
      DOCKER_HOST: "unix:///drone/docker.sock"
      RUST_BACKTRACE: 1
      RUST_LOG: debug
    commands:
      - docker -v
      - echo "$ABUILD_PUBKEY" >alpine@msrd0.de-5fc3c0b2.rsa.pub
      - echo "$ABUILD_PRIVKEY" >alpine@msrd0.de-5fc3c0b2.rsa
      - sha256sum alpine@msrd0.de-5fc3c0b2.rsa.pub alpine@msrd0.de-5fc3c0b2.rsa
      - ./target/debug/alpine-rust
  
  - name: rebuild-cache
    image: meltwater/drone-cache:v1
    pull: always
    settings:
      backend: "filesystem"
      rebuild: true
      cache_key: '{{ .Repo.Name }}_{{ checksum "Cargo.lock" }}_{{ arch }}_{{ os }}'
      archive_format: "gzip"
      mount:
        - "target"
    volumes:
      - name: cache
        path: /tmp/cache

services:
  - name: docker
    image: docker:dind
    priviledged: true
    command: ['-H', 'unix:///drone/docker.sock']

volumes:
  - name: cache
    host:
      path: /var/lib/cache

...
