
# APKBUILD are shell files and Dockerfile's are similar to shell files so we
# might want to use a shell-like escaper in the future
[[escaper]]
# ::askama::Text does not escape anything
path = "::askama::Text"
extensions = ["APKBUILD", "Dockerfile"]