# -*- eval: (cargo-minor-mode 1) -*-

[package]
name = "alpine-rust"
version = "0.1.0"
authors = ["Dominic <git@msrd0.de>"]
edition = "2018"

[dependencies]
askama = "0.10"
log = "0.4"
pretty_env_logger = "0.4"
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.1"
toml = "0.5"
