# -*- eval: (cargo-minor-mode 1) -*-

[package]
name = "alpine-rust"
version = "0.1.0"
authors = ["Dominic <git@msrd0.de>"]
edition = "2018"

[dependencies]
askama = "0.10"
bollard = "0.9"
lazy_static = "1.4"
log = "0.4"
num_cpus = "1.13"
pretty_env_logger = "0.4"
serde = { version = "1.0", features = ["derive"] }
tar = "0.4"
tempfile = "3.1"
toml = "0.5"
tokio = { version = "0.2", features = ["macros", "rt-threaded"] }
